//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.05 at 09:49:59 AM PDT 
//


package com.walmart._2010.xmlschema.mtep.wmiheader;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.walmart._2010.xmlschema.mtep.wmiheader package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.walmart._2010.xmlschema.mtep.wmiheader
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Wmiheader.To }
     * 
     */
    public Wmiheader.To createWmiheaderTo() {
        return new Wmiheader.To();
    }

    /**
     * Create an instance of {@link Wmiheader.From.Contactinfo.Emailaddress }
     * 
     */
    public Wmiheader.From.Contactinfo.Emailaddress createWmiheaderFromContactinfoEmailaddress() {
        return new Wmiheader.From.Contactinfo.Emailaddress();
    }

    /**
     * Create an instance of {@link Wmiheader.From.Contactinfo.Contactphone }
     * 
     */
    public Wmiheader.From.Contactinfo.Contactphone createWmiheaderFromContactinfoContactphone() {
        return new Wmiheader.From.Contactinfo.Contactphone();
    }

    /**
     * Create an instance of {@link Wmiheader.From }
     * 
     */
    public Wmiheader.From createWmiheaderFrom() {
        return new Wmiheader.From();
    }

    /**
     * Create an instance of {@link Wmiheader }
     * 
     */
    public Wmiheader createWmiheader() {
        return new Wmiheader();
    }

    /**
     * Create an instance of {@link Wmiheader.From.Contactinfo }
     * 
     */
    public Wmiheader.From.Contactinfo createWmiheaderFromContactinfo() {
        return new Wmiheader.From.Contactinfo();
    }

}
