//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.05 at 10:04:52 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.walmart.com/2010/XMLSchema/MTEP/fulfillment/DSV/ItemXRef/Version1")
package com.walmart._2010.xmlschema.mtep.fulfillment.dsv.itemxref.version1;
