//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.05 at 10:04:52 AM PDT 
//


package com.walmart._2010.xmlschema.mtep.fulfillment.dsv.itemxref.version1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SKUID" type="{http://www.walmart.com/2010/XMLSchema/MTEP/DSV/common/datatypes}SKUNo_type"/>
 *         &lt;element name="UPC" type="{http://www.walmart.com/2010/XMLSchema/MTEP/DSV/common/datatypes}UPCNumber_type"/>
 *         &lt;element name="WIN" type="{http://www.walmart.com/2010/XMLSchema/MTEP/DSV/common/datatypes}WIN_type"/>
 *         &lt;element name="StatusCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;minLength value="1"/>
 *               &lt;enumeration value="A"/>
 *               &lt;enumeration value="I"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "skuid",
    "upc",
    "win",
    "statusCode"
})
@XmlRootElement(name = "SKU")
public class SKU {

    @XmlElement(name = "SKUID", required = true)
    protected String skuid;
    @XmlElement(name = "UPC", required = true)
    protected String upc;
    @XmlElement(name = "WIN", required = true)
    protected String win;
    @XmlElement(name = "StatusCode", required = true)
    protected String statusCode;

    /**
     * Gets the value of the skuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKUID() {
        return skuid;
    }

    /**
     * Sets the value of the skuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKUID(String value) {
        this.skuid = value;
    }

    /**
     * Gets the value of the upc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPC() {
        return upc;
    }

    /**
     * Sets the value of the upc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPC(String value) {
        this.upc = value;
    }

    /**
     * Gets the value of the win property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWIN() {
        return win;
    }

    /**
     * Sets the value of the win property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWIN(String value) {
        this.win = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

}
